title: Arryn Kayn's Portfolio
description: Welcome to my portfolio! I’m Arryn Kayn, an IT Specialist dedicated to building a solid foundation in technology, with a keen interest in Identity Access Management (IAM), cloud,  and systems integration. My experience encompasses networking and system administration, where I have successfully implemented and configured systems tailored to meet various needs. I am driven by a passion for continuous learning and improvement in the industry. I look forward to contributing to innovative projects that focus on security and efficiency, and I’m excited about the opportunities that lie ahead. Let’s connect and explore how we can work together to make a positive impact!
github:
  another_url: "https://Arryn-Kayn-portfolio.com"
github_username: CyberBearPaw
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-google-analytics
google_analytics: UA-XXXXXXXX-X
tactile:
  accent_color: "#ff5733"
  show_downloads: true
