title: "Arryn Kayn's Portfolio"
description: "Welcome to my portfolio! I am Arryn Kayn, an IT Specialist dedicated to building a solid foundation in technology."
github:
  another_url: "https://Arryn-Kayn-portfolio.com"
github_username: "CyberBearPaw"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-google-analytics
google_analytics: "UA-XXXXXXXX-X" # Replace with your actual tracking ID

# Temporary section for CSS
assets:
  - "assets/css/styles.css"
